artifact_uri: /home/linq/finance/qniverse/mlrun1/1/39a09649c4304df78813e9bd82b42bae/artifacts
end_time: 1733834427558
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 39a09649c4304df78813e9bd82b42bae
run_name: mlflow_recorder
run_uuid: 39a09649c4304df78813e9bd82b42bae
source_name: ''
source_type: 4
source_version: ''
start_time: 1733834379742
status: 4
tags: []
user_id: linq
