artifact_uri: /home/linq/finance/qniverse/mlrun1/1/c660594a7dad49358e0b94452af69d9b/artifacts
end_time: 1733823123040
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: c660594a7dad49358e0b94452af69d9b
run_name: mlflow_recorder
run_uuid: c660594a7dad49358e0b94452af69d9b
source_name: ''
source_type: 4
source_version: ''
start_time: 1733823019714
status: 4
tags: []
user_id: linq
