qlib_init:
  provider_uri: "/data/linq/.qlib/qlib_data/cn_data"
  region: cn

model_config: &model_config
  seq_len: 20
  pred_len: 1
  e_layers: 2
  factor: 3
  enc_in: 158
  patch_len: 4
  stride: 4
  c_out: 1
  d_model: 128
  d_ff: 128
  n_heads: 4
  dropout: 0.1
  activation: 'gelu'


task:
  model:
    class: QniverseModel
    module_path: src/model_backbone.py
    kwargs:
      lr: 0.0005
      n_epochs: 5
      # max_steps_per_epoch: None
      early_stop: 5
      seed: 2024
      logdir: output/patchtst
      model_type: PatchTST
      model_config: *model_config
      freeze_model: False
      model_init_state:
  dataset:
    class: MTSDatasetH
    kwargs:
      seq_len: 20
      horizon: 1
      batch_size: 32
  qlib_dataset:
    class: BENCH_A
    kwargs:
      market: csi300
      benchmark: SH000300 
      feat: Alpha158
      label: r1
