qlib_init:
  provider_uri: "/data/linq/.qlib/qlib_data/cn_data"
  region: cn

model_config: &model_config
  seq_len: 20
  pred_len: 1
  e_layers: 1
  d_layers: 1
  factor: 3
  enc_in: 158
  dec_in: 158
  c_out: 1
  d_model: 64
  d_ff: 32
  top_k:  0
  wavelet_scale: 4
  period_coeff: 0.05
  num_kernels: 6
  dropout: 0.1

task:
  model:
    class: QniverseModel
    module_path: src/model_backbone.py
    kwargs:
      lr: 0.0001
      n_epochs: 1000
      max_steps_per_epoch: 100
      early_stop: 3
      seed: 2024
      logdir: output/wftnet
      model_type: WFTNet
      model_config: *model_config
      freeze_model: False
      model_init_state:
  dataset:
    class: MTSDatasetH
    kwargs:
      seq_len: 20
      horizon: 1
      batch_size: 32
  qlib_dataset:
    class: BENCH_B
    kwargs:
      market: csi300
      benchmark: SH000300 
      feat: Alpha158
      label: r1
      