artifact_uri: /home/linq/finance/qniverse/mlrun1/1/4bf9f4d7ecd7493aadcc26e6c0c156f2/artifacts
end_time: 1733822959212
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 4bf9f4d7ecd7493aadcc26e6c0c156f2
run_name: mlflow_recorder
run_uuid: 4bf9f4d7ecd7493aadcc26e6c0c156f2
source_name: ''
source_type: 4
source_version: ''
start_time: 1733822907419
status: 4
tags: []
user_id: linq
