artifact_uri: /home/linq/finance/qniverse/mlrun1/1/28d27770528841fa903ab1ef39cfd055/artifacts
end_time: 1733823343209
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 28d27770528841fa903ab1ef39cfd055
run_name: mlflow_recorder
run_uuid: 28d27770528841fa903ab1ef39cfd055
source_name: ''
source_type: 4
source_version: ''
start_time: 1733823291887
status: 4
tags: []
user_id: linq
