artifact_uri: /home/linq/finance/qniverse/mlrun1/1/334f5d6482ad45099bb4f6733e5a7d4f/artifacts
end_time: 1733833887751
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 334f5d6482ad45099bb4f6733e5a7d4f
run_name: mlflow_recorder
run_uuid: 334f5d6482ad45099bb4f6733e5a7d4f
source_name: ''
source_type: 4
source_version: ''
start_time: 1733833845521
status: 4
tags: []
user_id: linq
