artifact_uri: /home/linq/finance/qniverse/mlrun1/1/3575d2ba65c64448aa093f11635a7c8e/artifacts
end_time: 1733836136096
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 3575d2ba65c64448aa093f11635a7c8e
run_name: mlflow_recorder
run_uuid: 3575d2ba65c64448aa093f11635a7c8e
source_name: ''
source_type: 4
source_version: ''
start_time: 1733836130102
status: 4
tags: []
user_id: linq
