artifact_uri: /home/linq/finance/qniverse/mlrun1/1/27dedc332a774925acc8d63be3910f4b/artifacts
end_time: 1733822445957
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 27dedc332a774925acc8d63be3910f4b
run_name: mlflow_recorder
run_uuid: 27dedc332a774925acc8d63be3910f4b
source_name: ''
source_type: 4
source_version: ''
start_time: 1733822365443
status: 4
tags: []
user_id: linq
