artifact_uri: /home/linq/finance/qniverse/mlrun1/1/96cbafd343954452b22d1bf939faef43/artifacts
end_time: 1733822614533
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 96cbafd343954452b22d1bf939faef43
run_name: mlflow_recorder
run_uuid: 96cbafd343954452b22d1bf939faef43
source_name: ''
source_type: 4
source_version: ''
start_time: 1733822504377
status: 4
tags: []
user_id: linq
