artifact_uri: /home/linq/finance/qniverse/mlrun1/1/2884981f0a6f49ad849fec27379bb83b/artifacts
end_time: 1733834746768
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 2884981f0a6f49ad849fec27379bb83b
run_name: mlflow_recorder
run_uuid: 2884981f0a6f49ad849fec27379bb83b
source_name: ''
source_type: 4
source_version: ''
start_time: 1733834464529
status: 4
tags: []
user_id: linq
