qlib_init:
  provider_uri: "/data/linq/.qlib/qlib_data/cn_data"
  region: cn


model_config: &model_config
  seq_len: 20
  pred_len: 1
  e_layers: 2
  factor: 3
  enc_in: 360
  down_sampling_window: 2
  channel_independence: True
  moving_avg: 25
  down_sampling_layers: 3
  decomp_method: 'moving_avg'
  down_sampling_method: 'avg'
  embed: 'timeF'
  freq: 'd'
  c_out: 1
  d_model: 64
  d_ff: 32
  n_heads: 4
  dropout: 0.1
  activation: 'gelu'


task:
  model:
    class: QniverseModel
    module_path: src/model_backbone.py
    kwargs:
      lr: 0.0001
      n_epochs: 1
      max_steps_per_epoch: 5000
      early_stop: 1
      seed: 2024
      logdir: output/hs1124/timemixer
      model_type: TimeMixer
      model_config: *model_config
      freeze_model: False
      model_init_state:
  dataset:
    class: MTSDatasetH
    kwargs:
      seq_len: 20
      horizon: 1
      batch_size: 32
  qlib_dataset:
    class: BENCH_LPY
    kwargs:
      market: csi300_ext
      benchmark: SH000300 
      feat: Alpha360
      label: r1


strategy_config: &strategy_config
  topk: 10
  bad_thresh: -0.006
  hold_thresh: 2
