artifact_uri: /home/linq/finance/qniverse/mlrun1/1/82b6559d2bf24893becc142079b1ff27/artifacts
end_time: 1733822688791
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 82b6559d2bf24893becc142079b1ff27
run_name: mlflow_recorder
run_uuid: 82b6559d2bf24893becc142079b1ff27
source_name: ''
source_type: 4
source_version: ''
start_time: 1733822642602
status: 4
tags: []
user_id: linq
