artifact_uri: /home/linq/finance/qniverse/mlrun1/1/c8c964f748c94ae98d34f15ab9ad2618/artifacts
end_time: 1733835006844
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: c8c964f748c94ae98d34f15ab9ad2618
run_name: mlflow_recorder
run_uuid: c8c964f748c94ae98d34f15ab9ad2618
source_name: ''
source_type: 4
source_version: ''
start_time: 1733834966759
status: 4
tags: []
user_id: linq
