artifact_uri: /home/linq/finance/qniverse/mlrun1/1/cd9b9c901c634b00b283dd27ec33ec79/artifacts
end_time: 1733833682415
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: cd9b9c901c634b00b283dd27ec33ec79
run_name: mlflow_recorder
run_uuid: cd9b9c901c634b00b283dd27ec33ec79
source_name: ''
source_type: 4
source_version: ''
start_time: 1733827200772
status: 4
tags: []
user_id: linq
