artifact_uri: /home/linq/finance/qniverse/mlrun1/1/8cabccc225724acbbaaed750ff229def/artifacts
end_time: 1733825939493
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 8cabccc225724acbbaaed750ff229def
run_name: mlflow_recorder
run_uuid: 8cabccc225724acbbaaed750ff229def
source_name: ''
source_type: 4
source_version: ''
start_time: 1733825922074
status: 4
tags: []
user_id: linq
