artifact_uri: /home/linq/finance/qniverse/mlrun1/1/d1a0dbb7de764526a670f42b8e7f1280/artifacts
end_time: 1733826515275
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: d1a0dbb7de764526a670f42b8e7f1280
run_name: mlflow_recorder
run_uuid: d1a0dbb7de764526a670f42b8e7f1280
source_name: ''
source_type: 4
source_version: ''
start_time: 1733826506335
status: 4
tags: []
user_id: linq
