artifact_uri: /home/linq/finance/qniverse/mlrun1/1/72c20eb261d34ba88cc30740504778bb/artifacts
end_time: 1733833765607
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 72c20eb261d34ba88cc30740504778bb
run_name: mlflow_recorder
run_uuid: 72c20eb261d34ba88cc30740504778bb
source_name: ''
source_type: 4
source_version: ''
start_time: 1733833729708
status: 4
tags: []
user_id: linq
