artifact_uri: /home/linq/finance/qniverse/mlrun1/1/8b9157545fee49abba27115f9231f245/artifacts
end_time: 1733825800515
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 8b9157545fee49abba27115f9231f245
run_name: mlflow_recorder
run_uuid: 8b9157545fee49abba27115f9231f245
source_name: ''
source_type: 4
source_version: ''
start_time: 1733825542988
status: 3
tags: []
user_id: linq
