artifact_uri: /home/linq/finance/qniverse/mlrun1/1/913dbf1a80f3489184d9e7836f50ff6a/artifacts
end_time: 1733834821918
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 913dbf1a80f3489184d9e7836f50ff6a
run_name: mlflow_recorder
run_uuid: 913dbf1a80f3489184d9e7836f50ff6a
source_name: ''
source_type: 4
source_version: ''
start_time: 1733834786945
status: 4
tags: []
user_id: linq
