artifact_uri: /home/linq/finance/qniverse/mlrun1/1/2af0589d1a6b44de8d3d2e522fec86b2/artifacts
end_time: 1733825542984
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 2af0589d1a6b44de8d3d2e522fec86b2
run_name: mlflow_recorder
run_uuid: 2af0589d1a6b44de8d3d2e522fec86b2
source_name: ''
source_type: 4
source_version: ''
start_time: 1733825284441
status: 3
tags: []
user_id: linq
