artifact_uri: /home/linq/finance/qniverse/mlrun1/1/4ae1cc4c5ad6480a8f72025653b07826/artifacts
end_time: 1733826506328
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 4ae1cc4c5ad6480a8f72025653b07826
run_name: mlflow_recorder
run_uuid: 4ae1cc4c5ad6480a8f72025653b07826
source_name: ''
source_type: 4
source_version: ''
start_time: 1733826255135
status: 3
tags: []
user_id: linq
