artifact_uri: /home/linq/finance/qniverse/mlrun1/1/c28525eeaf564cc28898c740711d4d22/artifacts
end_time: 1733834333310
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: c28525eeaf564cc28898c740711d4d22
run_name: mlflow_recorder
run_uuid: c28525eeaf564cc28898c740711d4d22
source_name: ''
source_type: 4
source_version: ''
start_time: 1733834112410
status: 4
tags: []
user_id: linq
