artifact_uri: /home/linq/finance/qniverse/mlrun1/1/e2f013477ffd47098f0d39e4c0894c63/artifacts
end_time: 1733823519276
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: e2f013477ffd47098f0d39e4c0894c63
run_name: mlflow_recorder
run_uuid: e2f013477ffd47098f0d39e4c0894c63
source_name: ''
source_type: 4
source_version: ''
start_time: 1733823388693
status: 4
tags: []
user_id: linq
