artifact_uri: /home/linq/finance/qniverse/mlrun1/1/a77e976c5c7647da9b46db094410616e/artifacts
end_time: 1733822789247
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: a77e976c5c7647da9b46db094410616e
run_name: mlflow_recorder
run_uuid: a77e976c5c7647da9b46db094410616e
source_name: ''
source_type: 4
source_version: ''
start_time: 1733822716964
status: 4
tags: []
user_id: linq
