artifact_uri: /home/linq/finance/qniverse/mlrun1/1/c88a23be34944bdbb1a140696545e5fb/artifacts
end_time: 1733835898146
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: c88a23be34944bdbb1a140696545e5fb
run_name: mlflow_recorder
run_uuid: c88a23be34944bdbb1a140696545e5fb
source_name: ''
source_type: 4
source_version: ''
start_time: 1733835429256
status: 4
tags: []
user_id: linq
